---
title: "AllSierras_Historical"
output: html_document
---

```{r include=FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(dataRetrieval)
library(sf)
library(maps)
library(sp)
library(ncdf4)
library(sf)
library(sp)
library(lwgeom)
library(terra)
library(raster)
library(mapview)
library(tidyterra)
library(viridis)
library(MetBrewer)
library(stars)
library(data.table)
library(tigris)
library(patchwork)
library(car)
library(multcomp)
```

#Input Files (all together)
```{r}
AllSierras_DamCapacity <- readRDS("AllSierras_DamCapacity_volume.rds")
PADUS <- readRDS("PADUS.rds")
WatershedBoundaries <- readRDS("WatershedBoundaries.rds")
PADUS_clip <- readRDS("PADUS_clip.rds")
PADUS_Gap12 <- readRDS("PADUS_Gap12.rds")
DamCap_GAP12 <- readRDS("DamCap_GAP12.rds")
TNC_DamCapacity <- readRDS("TNC_DamCapacity.rds")

```
##Map
```{r}
palette_new <- colorRampPalette(colors = c("#ff0000", "#ffa500", "#ffff00", "#00FF50", "#4900FF"))(5)
#scales::show_col(palette_new)

c <- ggplot() +
    #geom_sf(data = background, fill = "#dcdcdc", lwd = 0.1)+
    geom_sf(data = transform(AllSierras_DamCapacity, DamCapacity=cut(oCC_EX, breaks = c(0,.1,2,5,15,40), include.lowest=T)),aes(color = DamCapacity)) +
    scale_color_manual(values=palette_new)+
    theme_minimal()+
    ggtitle(expression(paste("Current Dam Capacity"))) +
    theme(plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5)) +
    theme(element_text(size=10),legend.position = c(.15,.2))+
    labs(color = "dams/km", size=10)+
    theme(panel.border = element_rect(colour = "black", fill=NA))

```

```{r}
h <- ggplot() +
    #geom_sf(data = background, fill = "#dcdcdc", lwd = 0.1)+
    geom_sf(data = transform(AllSierras_DamCapacity, DamCapacity=cut(oCC_HPE, breaks = c(0,.1,2,5,15,40), include.lowest=T)),aes(color = DamCapacity)) +
    scale_color_manual(values=palette_new)+
    theme_minimal()+
    ggtitle(expression(paste("Historical Dam Capacity"))) +
    theme(plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5)) +
    theme(element_text(size=10),legend.position = c(.15,.2))+
    labs(color = "dams/km", size=10)+
    theme(panel.border = element_rect(colour = "black", fill=NA))

```

```{r}
(h + c)
```
##Calculate Historical Percent Remaining
```{r}
AllSierras_DamCapacity$mCC_EXvHPE <- AllSierras_DamCapacity$oCC_EX/AllSierras_DamCapacity$oCC_HPE
#When doing this division, sometimes we get 0/0 = Inf, especially in areas that are slope limited. In one way of looking at it, these values should be converted to 1, since dam capacity stayed the same from historic to current. However we converted them to NA? 
AllSierras_DamCapacity$mCC_EXvHPE[!is.finite(AllSierras_DamCapacity$mCC_EXvHPE)] <- NA
summary(AllSierras_DamCapacity$mCC_EXvHPE)
```


```{r}
mean(AllSierras_DamCapacity$mCC_EXvHPE, na.rm=T)#60% dam cap remaining by capacity 
existingsum <- sum(AllSierras_DamCapacity$mCC_EX_CT)
historicalsum <- sum(AllSierras_DamCapacity$mCC_HPE_CT)
existingsum/historicalsum # 51% dam cap remaining by count

```
##Ttest dam cap remaining
```{r}
ggplot(data = AllSierras_DamCapacity, aes(x=Protected, y = (mCC_EXvHPE)))+
         geom_boxplot()+
         theme_minimal()
       
leveneTest(mCC_EXvHPE~Protected, data = AllSierras_DamCapacity)#significant
ttest_1 <- t.test(mCC_EXvHPE ~ Protected, data = AllSierras_DamCapacity)
summary(ttest_1)
ttest_1

```
```{r}
r <- ggplot() +
    #geom_sf(data = background, fill = "#dcdcdc", lwd = 0.1)+
    geom_sf(data = transform(AllSierras_DamCapacity, DamCapacity=cut(mCC_EXvHPE, breaks = c(0,.25,.5,.75,1,70), include.lowest=T)),aes(color = DamCapacity)) +
    scale_color_manual(values=palette_new)+
    theme_minimal()+
    ggtitle(expression(paste("Percent Dam Capacity Remaining"))) +
    theme(plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5)) +
    theme(element_text(size=10),legend.position = c(.15,.2))+
    labs(color = "dams/km", size=10)+
    theme(panel.border = element_rect(colour = "black", fill=NA))
r
```
##Ttest Percent Dam Cap remaining, GAP and Other
```{r}
AllSierras_DamCapacity <- st_join(AllSierras_DamCapacity, PADUS_Gap12)

```

```{r}

AllSierras_DamCapacity$Protected <- with(AllSierras_DamCapacity, ifelse(is.na(AllSierras_DamCapacity$GAP_Sts), "Other", "GAP 1 & 2"))
AllSierras_DamCapacity$Protected <- as.factor(AllSierras_DamCapacity$Protected)

ggplot(data = AllSierras_DamCapacity, aes(x=Protected, y = (mCC_EXvHPE)))+
         geom_boxplot()+
         theme_minimal()
       
leveneTest(mCC_EXvHPE~Protected, data = AllSierras_DamCapacity)#significant
ttest_1 <- t.test(mCC_EXvHPE ~ Protected, data = AllSierras_DamCapacity)
summary(ttest_1)
ttest_1

```

##Total dams lost
```{r}
gap <- subset(AllSierras_DamCapacity, Protected == "GAP 1 & 2")
other <- subset(AllSierras_DamCapacity, Protected == "Other")

p1 <- ggplot()+
  geom_boxplot(data = gap, aes(x=Protected, y = sqrt(mCC_EXvHPE)), fill = "#e78429")+
  geom_boxplot(data = other, aes(x=Protected, y = sqrt(mCC_EXvHPE)), fill= "grey60")+
  theme_minimal() +
  ggtitle(expression(paste("% Change in Dam Capacity"))) + 
  xlab("Protection Status")+
  ylab("Sqrt % Change in Dam Capacity")+
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5)) +
  #theme(legend.position = c(.15,.15))+
  labs(shape = "")+
  theme(panel.border = element_rect(colour = "black", fill=NA))

```

##ANOVA within GAP 12
```{r}
###Clip BRAT to GAP 1 and 2 area
DamCap_GAP12 = st_intersection(AllSierras_DamCapacity, PADUS_Gap12)
DamCap_GAP12$FeatClass <- as.factor(DamCap_GAP12$FeatClass)
                                    
ggplot(data = DamCap_GAP12, aes(x=FeatClass, y = log(mCC_EXvHPE)))+
         geom_boxplot()+
         theme_minimal()
       
leveneTest(mCC_EXvHPE~FeatClass, data = DamCap_GAP12)#significant
anova1 <- aov(mCC_EXvHPE ~ FeatClass, data = DamCap_GAP12)
anova1_residuals <- residuals(object = anova1)

ggplot(anova1, aes(x = .fitted, y = .resid))+
  geom_point() + theme_classic()#bad
#shapiro.test(x = anova1_residuals)#too big

#try square root transformation
DamCap_GAP12 <- DamCap_GAP12 %>% mutate(sqrtvalue=sqrt(mCC_EXvHPE))
anova2 <- aov(sqrtvalue ~ FeatClass, data = DamCap_GAP12)

ggplot(data = DamCap_GAP12, aes(x=FeatClass, y = (sqrtvalue)))+
         geom_boxplot()+
         theme_minimal()

leveneTest(sqrtvalue~FeatClass, data = DamCap_GAP12)#significant

kruskal.test(sqrtvalue ~ FeatClass, data = DamCap_GAP12)

#PostHoc on the square root transformation
summary(anova2)
tukey <- TukeyHSD(anova2)
print(tukey)
```

```{r}
desig <- subset(DamCap_GAP12, FeatClass == "Designation")
fee <- subset(DamCap_GAP12, FeatClass == "Fee")
easement <- subset(DamCap_GAP12, FeatClass == "Easement")


p2 <- ggplot()+
  geom_boxplot(data = desig, aes(x=FeatClass, y = sqrt(mCC_EXvHPE)), fill = "#88a0dc") +
  geom_boxplot(data = fee, aes(x=FeatClass, y = sqrt(mCC_EXvHPE)), fill = "#ed968c") +
  geom_boxplot(data = easement, aes(x=FeatClass, y = sqrt(mCC_EXvHPE)), fill = "#f9d14a") +
  theme_minimal() +
  ggtitle(expression(paste("% Change in Dam Capacity"))) + 
  xlab("Land Ownership Type")+
  ylab("Sqrt % Change in Dam Capacity")+
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5)) +
  #theme(legend.position = c(.15,.15))+
  labs(shape = "")+
  theme(panel.border = element_rect(colour = "black", fill=NA))

```
```{r}
p1 + p2
```
#Change in veg suitability
```{r}
AllSierras_DamCapacity$VegChange100 <-  AllSierras_DamCapacity$iVeg100EX - AllSierras_DamCapacity$iVeg100Hpe 

```


```{r}

veg <- ggplot() +
    geom_sf(data = AllSierras_DamCapacity, aes(color = VegChange100)) +
    scale_color_gradient2(low = "red", mid = "white", high = "blue", midpoint = 0, na.value = "grey70")+
    xlab(NULL)+
    ylab(NULL)+
    ggtitle(expression(paste("Vegetation Change"))) + 
    theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5)) 
```
#Change in volume
##Historical volume
```{r}
for (i in AllSierras_DamCapacity){ #for each stream segment in the BRAT model output shapefile
  damCt <- AllSierras_DamCapacity$mCC_HPE_CT #number of beaver dams per segment (calculated based on dam density and segment length as the column mCC_HPE_CT in the attribute table)
  slope <- AllSierras_DamCapacity$iGeo_Slope #meters
  da <- AllSierras_DamCapacity$iGeo_DA #m2
  width <- ifelse(da < 4.95,2.18*(da)^0.191,
                  ifelse(da >= 4.95 & da < 377,1.41*(da)^0.462,7.18*(da)^0.183)) #based on Scamardo et al. 2022
  height <- 1 #assume all beaver dams are 1m tall
  length <- height/slope #trigonometry: slope = rise/run, so run = rise/slope
  maxLength<- (AllSierras_DamCapacity$iGeo_Len/damCt) #set a maximum length so that we can change volume calculations if there are so many dams that they all run together
  volumeHist <- ifelse(length < maxLength, 0.5*(height)*(width)*(length)*(damCt),(height)*(width)*(maxLength)*(damCt))
  surfaceAreaHist <- ifelse(length < maxLength, (width)*(length)*(damCt),(width)*(maxLength)*(damCt))
  AllSierras_DamCapacity$width <- width
  AllSierras_DamCapacity$volumeHist <- volumeHist #m3
  AllSierras_DamCapacity$surfaceAreaHist <- surfaceAreaHist #m2
} 

```

#Ma
```{r}
ggplot() +
    geom_sf(data = AllSierras_DamCapacity, aes(color = volumeHist)) +
    scale_color_viridis(discrete = FALSE, option = "plasma", na.value = "grey70")+
    xlab(NULL)+
    ylab(NULL)+
    ggtitle(expression(paste("Potential Water Storage (m3)"))) + 
    theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5)) 
```
##Volume Change
```{r}
AllSierras_DamCapacity$VolumeChange <-  AllSierras_DamCapacity$volume - AllSierras_DamCapacity$volumeHist

```

```{r}
vol <- ggplot() +
    geom_sf(data = AllSierras_DamCapacity, aes(color = VolumeChange)) +
    scale_color_gradient2(low = "red", mid = "grey70", high = "blue", midpoint = 0, na.value = "grey70")+
    xlab(NULL)+
    ylab(NULL)+
    ggtitle(expression(paste("Change in Volume (m3)"))) + 
    theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5)) 
```

```{r}
vol + veg
```
##Summarize with numbers
```{r}
sum(AllSierras_DamCapacity$VolumeChange )
currentstor <- sum(AllSierras_DamCapacity$volume)
historicalstor <- sum(AllSierras_DamCapacity$volumeHist)
percentleft <- currentstor/historicalstor

volchange <- currentstor-historicalstor
```
#Limitations
```{r}
unique(AllSierras_DamCapacity$oPBRC_UD)
length(AllSierras_DamCapacity$oPBRC_UD)


DamBuildingPossible <- (length(AllSierras_DamCapacity$oPBRC_UD[AllSierras_DamCapacity$oPBRC_UD == "Dam Building Possible"]))/(length(AllSierras_DamCapacity$oPBRC_UD))

StreamPowerLimited <- (length(AllSierras_DamCapacity$oPBRC_UD[AllSierras_DamCapacity$oPBRC_UD == "Stream Power Limited"]))/(length(AllSierras_DamCapacity$oPBRC_UD))

NaturallyVegetationLimited <- (length(AllSierras_DamCapacity$oPBRC_UD[AllSierras_DamCapacity$oPBRC_UD == "Naturally Vegetation Limited"]))/(length(AllSierras_DamCapacity$oPBRC_UD))

StreamSizeLimited <- (length(AllSierras_DamCapacity$oPBRC_UD[AllSierras_DamCapacity$oPBRC_UD == "Stream Size Limited"]))/(length(AllSierras_DamCapacity$oPBRC_UD))

PotentialReservoir <- (length(AllSierras_DamCapacity$oPBRC_UD[AllSierras_DamCapacity$oPBRC_UD == "Potential Reservoir or Landuse"]))/(length(AllSierras_DamCapacity$oPBRC_UD))

SlopeLimited <- (length(AllSierras_DamCapacity$oPBRC_UD[AllSierras_DamCapacity$oPBRC_UD == "Slope Limited"]))/(length(AllSierras_DamCapacity$oPBRC_UD))

AnthropogenicallyLimited <- (length(AllSierras_DamCapacity$oPBRC_UD[AllSierras_DamCapacity$oPBRC_UD == "Anthropogenically Limited"]))/(length(AllSierras_DamCapacity$oPBRC_UD))

a <- c('DamBuildingPossible','StreamPowerLimited','NaturallyVegetationLimited','StreamSizeLimited','PotentialReservoir','SlopeLimited','AnthropogenicallyLimited') 
b <- c(DamBuildingPossible,StreamPowerLimited,NaturallyVegetationLimited,StreamSizeLimited,PotentialReservoir,SlopeLimited,AnthropogenicallyLimited) 
df <- data.frame(a,b)

colnames(df) <- c("Limitation", "Proportion")
df$Percent <- df$Proportion * 100
df
```


















