---
title: "UpperMerced_NetCDF"
output: html_document
date: "2023-05-09"
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(dataRetrieval)
library(ggsn)
library(sf)
library(maps)
library(terra)
#install.packages('terra', repos='https://rspatial.r-universe.dev')

```
#Read in data
```{r}
vol_by_grid3_wgs <- readRDS('vol_by_grid3_wgs.rds')
```

###Convert to Raster
```{r}
r.vol <- rast(vol_by_grid3, xmin = -87159.4, ymin = -76403.81, xmax = 65400.97, ymax = -9900.421,resolution = (c(1000,1000)))
values(r.vol) <- vol_by_grid3$total_vol_in_cell 
r.vol
#see how many columns and rows we need 

#now do a real one
r.vol <- rast(ncols = 153, nrows = 67, xmin = -120.985, xmax = -119.255, ymin = 37.325, ymax = 37.925)
r.vol
values(r.vol) <- vol_by_grid3$total_vol_in_cell 
r.vol  <- terra::flip(r.vol, direction="vertical")
plot(r.vol,1, colNA="grey70")
```


```{r}
terra::writeRaster(r.vol, 'r.vol.tif', overwrite=TRUE)

```
#Surface Area
##Read in Data
```{r}
sa_by_grid3 <- readRDS('sa_by_grid3.rds')

```


###Convert to Raster
```{r}
r.sa <- rast(sa_by_grid3, xmin = -87159.4, ymin = -76403.81, xmax = 65840.6, ymax = -9403.811,resolution = (c(1000,1000)))
values(r.sa) <- sa_by_grid3$total_sa_in_cell 
#see how many columns and rows we need 

#now do a real one
r.sa <- rast(ncols = 153, nrows = 67, xmin = -120.985, xmax = -119.255, ymin = 37.325, ymax = 37.925)
r.vol
values(r.sa) <- sa_by_grid3$total_sa_in_cell 
r.sa  <- terra::flip(r.sa, direction="vertical")
plot(r.sa,1, colNA="grey70")

```

```{r}
terra::writeRaster(r.sa, 'r.sa.tif', overwrite=TRUE)

```
