---
title: "UpperMerced_BeaverDamLocations"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(dataRetrieval)
library(ggsn)
library(sf)
library(maps)
```
#Maps
##Get UM boundary shapefile
```{r}
getwd()

# Unzip the shapefile
#unzip("WBD_18_HU2_Shape.zip")

# Read in the shapefile with st_read()
#shapefile <- st_read("C:/Users/jessi/Desktop/SierraNevadaBeavers/SierraNevadaBeavers/Shape/WBDHU8.shp")

# Select just the Upper Merced Watershed
#UM_boundary <- st_write(shapefile[shapefile$huc8=="18040008",], "UM_boundary.shp", append = FALSE)

#remove unneeded shapefiles
#file.remove(list.files(pattern = "WBD_18_HU2_Shape*",recursive = F))

#Project to California Teal Albers (NAD83) EPSG code 3310
#UM_boundary <- st_transform(UM_boundary, 3310)

#saveRDS(UM_boundary,"UM_boundary")
UM_boundary <- readRDS("UM_boundary")

```
##UM Boundary Map
```{r}
ggplot() +
    geom_sf(data = UM_boundary) +
    xlab(NULL)+
    ylab(NULL)+
    ggtitle("Upper Merced)") + 
    theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5)) +
    north(UM_boundary, symbol=10, location="bottomright") + 
    scalebar(UM_boundary,
             dist=10, dist_unit="km", st.size = 3,
             transform=FALSE)
```

#Import Practice Shapefile

```{r}
getwd()

# Read in the shapefile with st_read()
#damCapClip <- st_read("C:/Users/jessie_moravek/Desktop/SierraNevadaBeavers/DamCapacity_Clip.shp")

#remove unneeded shapefiles
#file.remove(list.files(pattern = "DamCapacity_Clip*",recursive = F))

#Project to California Teal Albers (NAD83) EPSG code 3310
#damCapClip <- st_transform(damCapClip, 3310)

#saveRDS(damCapClip,"damCapClip.shp")
damCapClip <- readRDS("damCapClip.shp")
```
##Visualize
```{r}
ggplot() +
    geom_sf(data = damCapClip) +
    xlab(NULL)+
    ylab(NULL)+
    ggtitle("Dam Capacity Clipped Area") + 
    theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5)) +
    north(damCapClip, symbol=10, location="bottomright") + 
    scalebar(damCapClip,
             dist=.5, dist_unit="km", st.size = 3,
             transform=FALSE)
```

```{r}
damCapClip
#26 segments
#type: LINESTRING
str(damCapClip)
```
#Prep for Function
##Extract starting coordinates
```{r}
#Extract the start points of each stream segment
pts <- st_line_sample(damCapClip, sample = 0)

```

```{r}
ggplot() +
    geom_sf(data = damCapClip) +
    geom_sf(data = pts)+
    xlab(NULL)+
    ylab(NULL)+
    ggtitle("Dam Capacity Clipped Area") + 
    theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5)) +
    north(damCapClip, symbol=10, location="bottomright") + 
    scalebar(damCapClip,
             dist=.5, dist_unit="km", st.size = 3,
             transform=FALSE)
```
##Create damdist for loop
```{r}
#create boundary points with 500-meter spacing 
for (i in damCapClip){
  damdist <- ((damCapClip$iGeo_Len)*0.001)/(damCapClip$mCC_EX_CT)
  div.pts <- purrr::map(pts, function(x){evenspace(x, damdist)}) 
}
  damSubset <- st_coordinates(damCapClip)
  damCoord <- damSubset[,1:2]   
 # here you call the evenspace function.

length(div.pts) # this returns a MULTIPOINTS (or POINTS, if your input is LINESTRING), from which you can extract the coordinates. 
```




##Intersecting lines
```{r}
intersection <- st_intersection(grid1, damCapClip) %>% 
  mutate(length = st_length(.)) %>% 
  st_drop_geometry() # complicates things in joins later on

grid1 <- grid1 %>% 
  left_join(intersection, by = "id")

plot(grid1["length"])
```

