---
title: "StreamGaugeQuery"
output: html_document
date: "2023-04-22"
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(dataRetrieval)
library(ggsn)
library(sf)
library('maps')
```
#Search for relevant parameters
##NLDAS parameters
  
```{r}
#read in all the NWIS parameter codes 
pcode <- readNWISpCode("all")

#temperature codes
tempCodes <- pcode[grep("temperature",
                      pcode$parameter_nm,
                      ignore.case=TRUE),]

tempCodes
#Temperature, air, degrees Celsius = 00020

#precipitation codes
precipCodes <- pcode[grep("precipitation",
                      pcode$parameter_nm,
                      ignore.case=TRUE),]

precipCodes
#Precipitation, mm = 99772
#Precipitation, cumulative, mm = 72194
```
#Temperature
##Count UM gauges
```{r}
UM_gauges <- whatNWISsites(huc="18040008", 
                          parameterCd='00020')
nrow(UM_gauges)
#there are 82 possible gauges in the Upper Merced

names(UM_gauges)

UM_gauges
```

##Get UM boundary shapefile
```{r}
getwd()

# Unzip the shapefile
#unzip("WBD_18_HU2_Shape.zip")

# Read in the shapefile with st_read()
shapefile <- st_read("C:/Users/jessi/Desktop/SierraNevadaBeavers/SierraNevadaBeavers/Shape/WBDHU8.shp")

# Select just the Upper Merced Watershed
UM_boundary <- st_write(shapefile[shapefile$huc8=="18040008",], "UM_boundary.shp", append = FALSE)

#remove unneeded shapefiles
file.remove(list.files(pattern = "WBD_18_HU2_Shape*",recursive = F))

#Project to California Teal Albers (NAD83) EPSG code 3310
UM_boundary <- st_transform(UM_boundary, 3310)
```

##Transform gauge point data
```{r}
#Make the gauges point file into a sf object. Note that in the st_as_sf function, crs needs to the projection the file is ALREADY IN, not the projection you want. Specify the projection you want using st_transform
sf_UM <- st_as_sf(UM_gauges, 
                  coords = c("dec_long_va", "dec_lat_va"),
                  crs = 4269)

#Reproject gauge points
sf_UM <- st_transform(sf_UM, 3310)
```

##Map
```{r}
ggplot() +
    geom_sf(data = UM_boundary) +
    geom_sf(data = sf_UM) + 
    xlab(NULL)+
    ylab(NULL)+
    ggtitle("Upper Merced: Air Temp (C) Gauge Locations (n = 72)") + 
    theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5)) +
    north(sf_UM, symbol=10, location="bottomright") + 
    scalebar(UM_boundary,
             dist=10, dist_unit="km", st.size = 3,
             transform=FALSE)
```
#Precipitation
##Count UM gauges
```{r}
UM_gauges2 <- whatNWISsites(huc="18040009", 
                          parameterCd='99772')
#No gauges in the Upper Merced that measure precipitation...

```
