---
title: "UpperMerced_Volumes"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(dataRetrieval)
library(ggsn)
library(sf)
library(maps)
```

#Maps
##Get UM boundary shapefile
```{r}
getwd()

# Unzip the shapefile
#unzip("WBD_18_HU2_Shape.zip")

# Read in the shapefile with st_read()
#shapefile <- st_read("C:/Users/jessi/Desktop/SierraNevadaBeavers/SierraNevadaBeavers/Shape/WBDHU8.shp")

# Select just the Upper Merced Watershed
#UM_boundary <- st_write(shapefile[shapefile$huc8=="18040008",], "UM_boundary.shp", append = FALSE)

#remove unneeded shapefiles
#file.remove(list.files(pattern = "WBD_18_HU2_Shape*",recursive = F))

#Project to California Teal Albers (NAD83) EPSG code 3310
#UM_boundary <- st_transform(UM_boundary, 3310)

#saveRDS(UM_boundary,"UM_boundary")
UM_boundary <- readRDS("UM_boundary")

```
##UM Boundary Map
```{r}
ggplot() +
    geom_sf(data = UM_boundary) +
    xlab(NULL)+
    ylab(NULL)+
    ggtitle("Upper Merced)") + 
    theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5)) +
    north(UM_boundary, symbol=10, location="bottomright") + 
    scalebar(UM_boundary,
             dist=10, dist_unit="km", st.size = 3,
             transform=FALSE)
```


#Import Practice Shapefile

```{r}
getwd()

# Read in the shapefile with st_read()
#damCapClip <- st_read("C:/Users/jessie_moravek/Desktop/SierraNevadaBeavers/DamCapacity_Clip.shp")

#remove unneeded shapefiles
#file.remove(list.files(pattern = "DamCapacity_Clip*",recursive = F))

#Project to California Teal Albers (NAD83) EPSG code 3310
#damCapClip <- st_transform(damCapClip, 3310)

#saveRDS(damCapClip,"damCapClip.shp")
damCapClip <- readRDS("damCapClip.shp")
```
##Visualize
```{r}
ggplot() +
    geom_sf(data = damCapClip) +
    xlab(NULL)+
    ylab(NULL)+
    ggtitle("Dam Capacity Clipped Area") + 
    theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5)) +
    north(damCapClip, symbol=10, location="bottomright") + 
    scalebar(damCapClip,
             dist=.5, dist_unit="km", st.size = 3,
             transform=FALSE)
```


##Attribute table
```{r}
names(damCapClip)
damCapClip$iGeo_Slope
```
#Volume and Surface Area calculation
```{r}
damCapClip_v <- damCapClip
for (i in damCapClip_v){
  slope <- damCapClip_v$iGeo_Slope #meters
  da <- damCapClip_v$iGeo_DA #m2
  width <- ifelse(da < 4.95,2.18*(da)^0.191,
                  ifelse(da >= 4.95 & da < 377,1.41*(da)^0.462,7.18*(da)^0.183))
  length <- 1/slope
  maxLength<- (damCapClip_v$iGeo_Len/damCapClip_v$mCC_EX_CT)
  volume <- ifelse(length < maxLength, 0.5*1*(width)*(length),1*(width)*(maxLength))
  surfaceArea <- ifelse(length < maxLength, (width)*(length),(width)*(maxLength))
  damCapClip_v$width <- width
  damCapClip_v$volume <- volume #m3
  damCapClip_v$surfaceArea <- surfaceArea #m2
} 

saveRDS(damCapClip_v,"damCapClip_v.rds")
```


##Create 1km grid
```{r}
#Check if sf object is in metric CRS (i.e. projected)
st_is_longlat(damCapClip)
#st_is_longlat returns "False" which means that the object damCapClip is in a metric CRS

#CRS 3310 is in units of meters (see here https://epsg.io/3310)
grid_spacing <- 1000 

grid1 <- st_make_grid(damCapClip, square = T, cellsize = c(grid_spacing, grid_spacing)) %>% # the grid, covering bounding box
  st_sf()

#add an id column
grid1 <- mutate(grid1, id = 1:nrow(grid1))
```




##Volume by grid cell
```{r}
intersection <- st_intersection(grid1, damCapClip_v) %>% 
  mutate(length = st_length(.)) %>% #creates a "length" column that is the length of that particular segment in the grid cell from the "id" column
  st_drop_geometry() # complicates things in joins later on

grid1 <- grid1 %>% 
  left_join(intersection, by = "id")

vol_by_grid <- grid1 %>% 
  mutate(percent_len_in_cell = length/iGeo_Len) %>% 
  mutate(segment_vol_in_cell = percent_len_in_cell*volume) %>% 
  group_by(id) %>% summarize(total_vol_in_cell = sum(segment_vol_in_cell))

vol_by_grid
vol_by_grid$total_vol_in_cell <- as.numeric(vol_by_grid$total_vol_in_cell) #convert volume col to numeric
```
```{r}
ggplot() +
    geom_sf(data = vol_by_grid, aes(fill = total_vol_in_cell), color = NA) +
    geom_sf(data = damCapClip, col = "blue") +
    scale_fill_gradient2(low = "#132B43", high = "#078FF7") +
    xlab(NULL)+
    ylab(NULL)+
    ggtitle( expression(paste("Volume per ", km^2))) + 
    theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5), 
          panel.grid.major = element_line(colour = "transparent")) +
    north(damCapClip, symbol=10, location="bottomleft") + 
    scalebar(vol_by_grid,
             dist=.5, dist_unit="km", st.size = 3, transform= F) +
    guides(fill = guide_colorbar(title = expression(paste(m^3)),
                             title.position = "bottom",
                             title.theme = element_text(size = 10,
                                                        colour = "gray70",
                                                        angle = 0)))

median(vol_by_grid$total_vol_in_cell,na.rm=T)
```

##Surface Area by grid cell
```{r}
#use grid1 (after doing the leftjoin above for volume calculations)

sa_by_grid <- grid1 %>% 
  mutate(percent_len_in_cell = length/iGeo_Len) %>% 
  mutate(segment_sa_in_cell = percent_len_in_cell*surfaceArea) %>% 
  group_by(id) %>% summarize(total_sa_in_cell = sum(segment_sa_in_cell))

sa_by_grid
sa_by_grid$total_sa_in_cell <- as.numeric(sa_by_grid$total_sa_in_cell) #convert volume col to numeric
```

```{r}
ggplot() +
    geom_sf(data = sa_by_grid, aes(fill = total_sa_in_cell), color = NA) +
    geom_sf(data = damCapClip, col = "blue") +
    scale_fill_gradient2(low = "#43132B", high = "#F7078F") +
    xlab(NULL)+
    ylab(NULL)+
    ggtitle( expression(paste("Surface Area per ", km^2))) + 
    theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5), 
          panel.grid.major = element_line(colour = "transparent")) +
    north(damCapClip, symbol=10, location="bottomleft") + 
    scalebar(vol_by_grid,
             dist=.5, dist_unit="km", st.size = 3, transform= F) +
    guides(fill = guide_colorbar(title = expression(paste(m^2)),
                             title.position = "bottom",
                             title.theme = element_text(size = 10,
                                                        colour = "gray70",
                                                        angle = 0)))

median(vol_by_grid$total_vol_in_cell,na.rm=T)
```

#Upper Merced
##Bounding Box
```{r}
#This box aligns with this LIS model coordinates
getwd()

# Read in the shapefile with st_read()
boundingBox <- st_read("C:/Users/jessie_moravek/Desktop/SierraNevadaBeavers/BoundingBox.shp")

#remove unneeded shapefiles
file.remove(list.files(pattern = "BoundingBox*",recursive = F))

#Project to California Teal Albers (NAD83) EPSG code 3310
boundingBox <- st_transform(boundingBox, 3310)

saveRDS(boundingBox,"boundingBox")
boundingBox <- readRDS("boundingBox")
```
##Dam Capacity
```{r}
#This box aligns with this LIS model coordinates
getwd()

# Read in the shapefile with st_read()
damCapacity <- st_read("C:/Users/jessie_moravek/Desktop/SierraNevadaBeavers/DamCapacity.shp")

#remove unneeded shapefiles
file.remove(list.files(pattern = "damCapacity*",recursive = F))

#Project to California Teal Albers (NAD83) EPSG code 3310
damCapacity <- st_transform(damCapacity, 3310)

saveRDS(damCapacity,"damCapacity")
damCapacity <- readRDS("damCapacity")
```
##Create 1km grid
```{r}
#Check if sf object is in metric CRS (i.e. projected)
st_is_longlat(boundingBox)
#st_is_longlat returns "False" which means that the object is in a metric CRS

#CRS 3310 is in units of meters (see here https://epsg.io/3310)
grid_spacing <- 1000 

grid2 <- st_make_grid(boundingBox, square = T, cellsize = c(grid_spacing, grid_spacing)) %>% # the grid, covering bounding box
  st_sf()

#add an id column
grid2 <- mutate(grid2, id = 1:nrow(grid2))
```

###Map
```{r}
ggplot() +
    geom_sf(data = grid2, fill = NA) +
    geom_sf(data = damCapacity, col = "blue") +
    xlab(NULL)+
    ylab(NULL)+
    ggtitle( expression(paste("Upper Merced 1km Grid"))) + 
    theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5), 
          panel.grid.major = element_line(colour = "transparent")) +
    north(damCapacity, symbol=10, location="bottomright") + 
    scalebar(damCapacity,
             dist=10, dist_unit="km", st.size = 3, transform= F) 
```
##Volume and Surface Area calculation
```{r}
damCapacity_v <- damCapacity
for (i in damCapacity_v){
  slope <- damCapacity_v$iGeo_Slope #meters
  da <- damCapacity_v$iGeo_DA #m2
  width <- ifelse(da < 4.95,2.18*(da)^0.191,
                  ifelse(da >= 4.95 & da < 377,1.41*(da)^0.462,7.18*(da)^0.183))
  length <- 1/slope
  maxLength<- (damCapacity_v$iGeo_Len/damCapacity_v$mCC_EX_CT)
  volume <- ifelse(length < maxLength, 0.5*1*(width)*(length),1*(width)*(maxLength))
  surfaceArea <- ifelse(length < maxLength, (width)*(length),(width)*(maxLength))
  damCapacity_v$width <- width
  damCapacity_v$volume <- volume #m3
  damCapacity_v$surfaceArea <- surfaceArea #m2
} 

saveRDS(damCapacity_v,"damCapacity_v.rds")
```

##Volume by grid cell
```{r}
intersection2 <- st_intersection(grid2, damCapacity_v) %>% 
  mutate(length = st_length(.)) %>% #creates a "length" column that is the length of that particular segment in the grid cell from the "id" column
  st_drop_geometry() # complicates things in joins later on

grid2 <- grid2 %>% 
  left_join(intersection2, by = "id")

vol_by_grid2 <- grid2 %>% 
  mutate(percent_len_in_cell = length/iGeo_Len) %>% 
  mutate(segment_vol_in_cell = percent_len_in_cell*volume) %>% 
  group_by(id) %>% summarize(total_vol_in_cell = sum(segment_vol_in_cell))

vol_by_grid2$total_vol_in_cell <- as.numeric(vol_by_grid2$total_vol_in_cell) #convert volume col to numeric
```
###Map
```{r}
ggplot() +
    geom_sf(data = vol_by_grid2, aes(fill = total_vol_in_cell), color = NA) +
    #geom_sf(data = damCapacity, col = "blue") +
    scale_fill_gradient2(limits = c(0,150), low = "#132B43", high = "#078FF7") +
    xlab(NULL)+
    ylab(NULL)+
    ggtitle( expression(paste("Volume per ", km^2))) + 
    theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5), 
          panel.grid.major = element_line(colour = "transparent")) +
    north(damCapacity, symbol=10, location="bottomleft") + 
    scalebar(vol_by_grid2,
             dist=20, dist_unit="km", st.size = 3, transform= F) +
    guides(fill = guide_colorbar(title = expression(paste(m^3)),
                             title.position = "bottom",
                             title.theme = element_text(size = 10,
                                                        colour = "gray70",
                                                        angle = 0)))
0:150
?scale_fill_gradient2
summary(vol_by_grid2$total_vol_in_cell,na.rm=T)
```
##Surface Area by grid cell
```{r}
#use grid2 (after doing the leftjoin above for volume calculations)

sa_by_grid2 <- grid2 %>% 
  mutate(percent_len_in_cell = length/iGeo_Len) %>% 
  mutate(segment_sa_in_cell = percent_len_in_cell*surfaceArea) %>% 
  group_by(id) %>% summarize(total_sa_in_cell = sum(segment_sa_in_cell))

sa_by_grid2$total_sa_in_cell <- as.numeric(sa_by_grid2$total_sa_in_cell) #convert volume col to numeric
```
###Map
```{r}
ggplot() +
    geom_sf(data = sa_by_grid2, aes(fill = total_sa_in_cell), color = NA) +
    #geom_sf(data = damCapacity, col = "blue") +
    scale_fill_gradient2(limits = c(0,150), low = "#43132B", high = "#F7078F") +
    xlab(NULL)+
    ylab(NULL)+
    ggtitle( expression(paste("Surface Area per ", km^2))) + 
    theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5), 
          panel.grid.major = element_line(colour = "transparent")) +
    north(damCapacity, symbol=10, location="bottomleft") + 
    scalebar(vol_by_grid2,
             dist=20, dist_unit="km", st.size = 3, transform= F) +
    guides(fill = guide_colorbar(title = expression(paste(m^2)),
                             title.position = "bottom",
                             title.theme = element_text(size = 10,
                                                        colour = "gray70",
                                                        angle = 0)))
0:150
?scale_fill_gradient2
summary(sa_by_grid2$total_sa_in_cell,na.rm=T)
```